version: "3.7"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: 
      sh -c "sleep 10 &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
