# Generated by Django 3.2.9 on 2021-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_surveymodel_finishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymodel',
            name='finishing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
