# Generated by Django 3.2.9 on 2021-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_alter_surveymodel_finishing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymodel',
            name='author',
        ),
    ]
