# Generated by Django 3.2.9 on 2021-11-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0005_remove_surveymodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymodel',
            name='voted_users',
        ),
    ]
