# Generated by Django 3.2.9 on 2021-11-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0009_auto_20211104_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='votes_counts',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
