# Generated by Django 3.2.9 on 2021-11-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0010_surveymodel_votes_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveymodel',
            old_name='answer_options',
            new_name='answers',
        ),
        migrations.RemoveField(
            model_name='surveymodel',
            name='votes_counts',
        ),
    ]
