# Generated by Django 3.2.9 on 2021-11-06 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting_app', '0011_auto_20211105_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersurveyjunctionmodel',
            unique_together={('user', 'survey')},
        ),
    ]
